### ISSUE TITLE
Include an *.XComMod file in each project.

### ISSUE THREAD

**Issue by rpavlov** [BlueRaja/XCom2Mods#1]
Hats off to ya, these mods rock! 

However, they won't work with the mod launcher if there's no .xcommod file included. You're probably already aware, but the structure looks like so (for Stop Wasting My Time)

```
[mod]
publishedFileId=620600092
Title=StopWastingMyTime
Description=LOL
```

**Comment by BlueRaja** [comment]
Wait, what mod launcher are you talking about?  My mods all work correctly with the launcher included with the game, as far as I've seen.  I also have not seen any other workshop mods with this file...

**Comment by rpavlov** [comment]
The one in binaries/win64/. 

I've only used mods from xcomnexus thus far, but they usually come with a .xcommod file. 

http://www.nexusmods.com/xcom2/mods/1/?tab=1&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fxcom2%2Fajax%2Fmoddescription%2F%3Fid%3D1%26preview%3D&pUp=1 is one example

**Comment by BlueRaja** [comment]
Ah, it must be a Nexus-specific thing _(or maybe a mods-installed-outside-Steam-workshop thing)_.

I plan on looking into how to release my mods on Nexus this weekend, so I will probably do this then.  Thanks!

**Comment by rpavlov** [comment]
Indeed, its a mods-installed-outside-Steam-workshop thing :)

Anyway, keep up the good work!

**Comment by HSMatheus** [comment]
Yeah please BlueRaja release this on Nexus <3

**Comment by BlueRaja** [comment]
Ok, I've uploaded most of my mods _(all of the popular ones, and a few others)_ to Nexus.  The files there include the `*.XComMod` file, though they are not included here because they are part of the build process, not part of the code.

Finally closing!

**Comment by rpavlov** [comment]
Yay! Hack the planet!!
