### ISSUE TITLE
where i install this mods ?

### ISSUE THREAD

**Issue by gabrielfsousa** [BlueRaja/XCom2Mods#4]
i had installed it here 

C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XComGame\Mods
C:\XCOM 2\XComGame\Mods
C:\Users\Vlad\Documents\My Games\XCOM2\XComGame\Mods

and they dont work. what i'm doing wrong ?

**Comment by BlueRaja** [comment]
Please use Steam Workshop or Nexusmods, this is just the source code, not the compiled output.
