### ISSUE TITLE
"Stop wasting my time" broken since Shen's Last Gift DLC

### ISSUE THREAD

**Issue by DireMunchkin** [BlueRaja/XCom2Mods#6]
Hi,
Since downloading Shen's Last Gift DLC I noticed a lot of the improvements for "Stop Wasting My Time" don't work anymore. I haven't tested exhaustively but I did notice these:
- avenger / skyranger move speed on the geoscape is back to normal
- scanning speed is back to normal
- revealed enemies cinematic time is back

**Comment by BlueRaja** [comment]
I just tested, and all of these things are still working correctly with the latest version of the mod + XCom 2 + DLCs.

It's possible you're having a conflict with another mod.  It's also possible you just don't notice the changes.  One of the goals of this mod is to speed things up _without_ making them look unnatural, so if you don't notice the mod working... that's a good thing!

Try comparing eg. the avenger speed with the mod enabled/disabled, and the difference should become obvious.  Note that the launcher doesn't disable mods correctly; you'll need to unsubscribe, or use the [alternative launcher](https://www.reddit.com/r/xcom2mods/comments/4ak5cv/alternative_mod_launcher/).

_(Also I'm not sure what "scanning speed is back to normal" means, SWMT doesn't change the scanning speed)_
